version: '3'
services:
    mysql:
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=app
            - MYSQL_DATABASE=app
        volumes:
            - ./docker/timeout.cnf:/etc/mysql/conf.d/timeout.cnf

    app:
        build: ./
        restart: always
        depends_on:
            - mysql
        environment:
            - BEHIND_PROXY=False
            - DATABASE_DSN=mysql+aiomysql://root:app@mysql:3306/app
            - UPLOAD_PATH=/app/uploads
            - TEMP_FILE_PATH=/app/temp_uploads
            - URL_PREFIX=/super_secret_url # admin panel's URL prefix, use http://example.com/super_secret_url/index.html to access it
            - LOGIN_PASSWORD=strong_password  # after first start, you can delete this line
        ports:
            - "80:80" # or if you want to reverse proxy, change BEHIND_PROXY=False to BEHIND_PROXY=True, and using X-Real-IP to trasnfer IP
            # - "127.0.0.1:8080:80"
