version: '3'
services:
    mysql:
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=app
            - MYSQL_DATABASE=app
        volumes:
            - ./docker/timeout.cnf:/etc/mysql/conf.d/timeout.cnf

    app:
        build: ./
        restart: always
        depends_on:
            - mysql
        environment:
            - FRONTEND_DIR=/app/docker/front_dist
            - BEHIND_PROXY=False
            - DATABASE_DSN=mysql+aiomysql://root:app@mysql:3306/app
            - UPLOAD_PATH=/app/uploads
            - TEMP_FILE_PATH=/app/temp_uploads
            - URL_PREFIX=/admin        # admin panel's URL prefix, use http://example.com/admin/index.html to access it
            - INIT_USER=admin:admin  # user created after first start
        ports:
            - "80:8080" # or if you want to reverse proxy, change BEHIND_PROXY=False to BEHIND_PROXY=True, and using X-Real-IP to trasnfer IP
            # - "127.0.0.1:8080:8080"
